[build-system]
requires = ["maturin>=1.9,<2"]
build-backend = "maturin"

[project]
name = "pyfastbloom"
version = "0.1.0"
requires-python = ">=3.12"

[tool.maturin]
features = ["pyo3/extension-module"]

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "Cargo.toml" }, { file = "**/*.rs" }]

[dependency-groups]
dev = [
    "maturin>=1.15.0",
    "ziglang>=0.16.0",
]
